export interface IFeatureFlagSeed {
  key: string;
  name: string;
  description: string;
  isEnabled: boolean;
  rolloutPercentage: number;
  targetAudience: "global" | "organizations" | "roles" | "percentage";
  environment: "all" | "production" | "staging" | "development";
}

export const DEFAULT_PLATFORM_FLAGS: IFeatureFlagSeed[] = [
  // ===========================================================================
  // 1. Identity, Authentication & Tenant Access (9 Capabilities)
  // ===========================================================================
  {
    key: "auth_credentials",
    name: "Password-Based Authentication",
    description: "Native username and password authentication with bcrypt password hashing",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "auth_session_revocation",
    name: "Secure Session Termination",
    description: "Immediate revocation of active JWT sessions and quarantine boundary enforcement",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "auth_self_registration",
    name: "Invitation & Self-Registration",
    description: "Candidate onboarding self-registration and invitation token intake",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "auth_password_reset",
    name: "Password Recovery & Reset",
    description: "Self-service password recovery workflows with time-limited tokens",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "sso_enforcement",
    name: "Enterprise SAML 2.0 / OIDC SSO",
    description: "Single Sign-On enforcement via corporate identity providers",
    isEnabled: false,
    rolloutPercentage: 0,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "auth_token_refresh",
    name: "JWT Token Auto-Renewal",
    description: "Seamless rotating refresh tokens for continuous active user sessions",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "rbac_route_protection",
    name: "Role Capability Guards",
    description: "Fine-grained role and capability boundaries on client and API routes",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "multi_org_switch",
    name: "Multi-Tenant Workspace Switcher",
    description: "Allows enterprise users to switch across multi-tenant workspaces",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "scim_provisioning",
    name: "SCIM 2.0 Automated User Sync",
    description: "Sync Okta, Azure AD, and Google Workspace identities via SCIM 2.0",
    isEnabled: false,
    rolloutPercentage: 0,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 2. Candidate Onboarding Experience (10 Capabilities)
  // ===========================================================================
  {
    key: "onboarding_roadmap",
    name: "Interactive Candidate Roadmap",
    description: "Visual multi-stage journey timeline and progress roadmap for candidates",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "digital_signatures",
    name: "Compliance Document E-Signatures",
    description: "Legally binding electronic signature collection on compliance PDFs",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "checklist_tasks",
    name: "Candidate Task Checklist",
    description: "Interactive pre-boarding and first-week task completion checklists",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "lms_course_player",
    name: "LMS Interactive Course Viewer",
    description: "In-app rich multimedia training content and SCORM learning player",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "lms_assessments",
    name: "Course Quizzes & Knowledge Checks",
    description: "Interactive knowledge verification quizzes and comprehension assessments",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "milestone_ratings",
    name: "30-60-90 Self-Rating Intake",
    description: "Structured 30, 60, and 90-day sentiment and milestone self-evaluations",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "buddy_connection",
    name: "Onboarding Buddy Chat & Info",
    description: "Dedicated mentor pairing with direct chat and scheduled touchpoints",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "graduation_handover",
    name: "Handover & Graduation Certificate",
    description: "Automated transition from candidate status to active team member",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "pwa_offline_sync",
    name: "Mobile PWA Offline Learning",
    description: "Progressive Web App support with IndexedDB offline sync capabilities",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "onboarding_copilot",
    name: "Onboarding AI Copilot",
    description: "Autonomous virtual assistant guiding candidates through onboarding steps",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 3. HR Administration & Journey Blueprinting (18 Capabilities)
  // ===========================================================================
  {
    key: "journey_templates",
    name: "Journey Template Authoring",
    description: "Create and maintain reusable multi-stage onboarding journey blueprints",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "journey_builder",
    name: "Visual Drag-and-Drop Builder",
    description: "Visual drag-and-drop workflow canvas for assembling custom journeys",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "step_prerequisites",
    name: "Dynamic Step Prerequisite Gating",
    description: "Sequential step gating based on predecessor task completion",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "employee_directory",
    name: "Employee Directory & Management",
    description: "Centralized staff roster with role assignment and status filtering",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "employee_invite",
    name: "Candidate Invitation Dispatch",
    description: "Direct email invitation dispatch with secure onboarding token links",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "bulk_csv_import",
    name: "Enterprise Bulk CSV Import",
    description: "High-throughput CSV candidate import with schema validation",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "workflow_rules",
    name: "Workflow Automation Rules Engine",
    description: "Rule-based automation triggers for candidate lifecycle transitions",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "workflow_actions",
    name: "Trigger-Condition-Action Builder",
    description: "Custom event-driven action builder for webhook and notification dispatch",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "hr_ops_dashboard",
    name: "HR Operations Velocity Dashboard",
    description: "Executive cockpit monitoring onboarding throughput and completion SLAs",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "hr_exceptions",
    name: "Exceptions Workbench & SLA Triage",
    description: "Operational workbench for triaging stalled tasks and escalation queues",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "doc_templates",
    name: "Document Template Designer",
    description: "PDF and HTML template creation with dynamic token interpolation",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "doc_field_markers",
    name: "PDF Field Positioning (Canvas)",
    description: "Visual coordinate mapping for signature, date, and initials fields",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "task_templates",
    name: "Standalone Task Template Builder",
    description: "Reusable role-specific task catalogs and assignment bundles",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "task_due_offsets",
    name: "Relative Due-Date Offset Rules",
    description: "Dynamic due-date scheduling calculated relative to hire start date",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "ai_course_builder",
    name: "AI Course Builder",
    description: "Generates structured onboarding courses using LLM intelligence",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "org_branding",
    name: "Org Branding, Logos & Themes",
    description: "Custom organization logos, brand color palettes, and welcome theming",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "advanced_hris_sync",
    name: "HRIS Integrations Marketplace",
    description: "Bi-directional employee record synchronization with Workday, BambooHR, and Rippling",
    isEnabled: false,
    rolloutPercentage: 0,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "tenant_analytics",
    name: "Executive Drop-Off Analytics",
    description: "Funnel analysis identifying candidate drop-off and friction stages",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 4. Team Supervision & Manager Operations (7 Capabilities)
  // ===========================================================================
  {
    key: "manager_dashboard",
    name: "Manager Team Operations View",
    description: "Manager cockpit for monitoring direct report onboarding journeys",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "direct_report_view",
    name: "Direct Report Progress Dossier",
    description: "Granular dossier view of individual candidate task completion and feedback",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "milestone_approval",
    name: "30-60-90 Milestone Approvals",
    description: "Manager evaluation and sign-off portal for probation milestones",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "task_verification",
    name: "Task Evidence & File Verification",
    description: "Manager approval workflow for candidate submitted documents and files",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "checkin_scheduler",
    name: "1-on-1 Check-In Meeting Scheduler",
    description: "Integrated calendar scheduling for weekly 1-on-1 manager syncs",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "buddy_assignment",
    name: "Direct Hire Buddy Pairing",
    description: "Manager interface for pairing new hires with experienced team mentors",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "team_velocity",
    name: "Team Velocity & SLA Alerting",
    description: "Real-time alerts for impending milestone deadlines and overdue items",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 5. Mentorship & Buddy Program (4 Capabilities)
  // ===========================================================================
  {
    key: "buddy_profile",
    name: "Buddy Profile & Capacity Setup",
    description: "Mentor profile declaration including skills, interests, and mentee capacity",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "mentee_tracking",
    name: "Mentee Progress Oversight",
    description: "Dedicated view for buddies to track mentee roadmap and milestone progress",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "buddy_feedback",
    name: "Check-in Sentiment & Notes Log",
    description: "Structured check-in notes and sentiment capture between buddy and mentee",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "smart_buddy_match",
    name: "Algorithmic Buddy Matching",
    description: "Machine learning matching based on department, interests, and timezone",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 6. Frontline & Touch Kiosk Systems (5 Capabilities)
  // ===========================================================================
  {
    key: "kiosk_pairing",
    name: "6-Digit Kiosk Device Pairing",
    description: "Secure 6-digit one-time code pairing for hardware tablet registration",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "kiosk_mode",
    name: "Touchscreen Kiosk Player Mode",
    description: "Dedicated fullscreen locked-down terminal interface for factory floor onboarding",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "kiosk_audio_sop",
    name: "High-Contrast Audio SOP Playback",
    description: "Audio narration and high-contrast visuals for frontline workplace safety",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "kiosk_safety_check",
    name: "Touch PPE Safety Checklists",
    description: "Touchscreen verification of mandatory safety gear and facility compliance",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "kiosk_telemetry",
    name: "Device Heartbeat & Offline Cache",
    description: "Local SQLite caching and background telemetry heartbeats for kiosk devices",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 7. IT Administration & Hardware Provisioning (4 Capabilities)
  // ===========================================================================
  {
    key: "it_ops_queue",
    name: "IT Hardware Provisioning Queue",
    description: "IT dispatch queue for staging laptops, peripherals, and security tokens",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "it_asset_tracking",
    name: "Asset Serial & Model Tagging",
    description: "Serial number, asset tag, and MDM profile assignment to new hires",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "it_shipping_flow",
    name: "Hardware Shipping & Delivery Flow",
    description: "Carrier tracking number capture and delivery confirmation workflow",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "it_access_setup",
    name: "Software Accounts Provisioning",
    description: "Checklist tracking for email, VPN, SaaS licenses, and security access",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 8. Engagement, Gamification & Recognition (5 Capabilities)
  // ===========================================================================
  {
    key: "gamified_milestones",
    name: "Learner Gamification Points Engine",
    description: "Award milestone achievements and learner leaderboard",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "gamification_badges",
    name: "Achievement Badges & Awards",
    description: "Digital unlockable badges for fast completion and perfect quiz scores",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "learner_streaks",
    name: "Daily Learning Streak Engine",
    description: "Motivational consecutive day login tracking with streak freeze protections",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "leaderboard_view",
    name: "Organization Leaderboard Page",
    description: "Tenant-wide friendly competition showing top onboarding points earners",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "level_progression",
    name: "Experience Level Progression",
    description: "Tiered level unlocks reflecting cumulative knowledge and completed tasks",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 9. Workplace Wayfinding, Maps & Scheduling (6 Capabilities)
  // ===========================================================================
  {
    key: "office_map",
    name: "Interactive Floorplan Map Viewer",
    description: "Interactive SVG architectural floorplans showing facilities and layouts",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "desk_pins",
    name: "Desk & Amenity Visual Pins",
    description: "Interactive markers designating assigned desks, restrooms, and emergency exits",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "map_wayfinding",
    name: "Visual Wayfinding & Pathfinding",
    description: "Visual step-by-step route navigation from reception to assigned workspace",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "calendar_integration",
    name: "Google / Outlook Calendar Sync",
    description: "Bi-directional synchronization with Google Calendar and Microsoft Outlook",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "meeting_automation",
    name: "Auto-Scheduled Orientation Meets",
    description: "Automated calendar invitation dispatch for cohorts and manager meets",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "ical_feed",
    name: "Personal iCal Calendar Feed URL",
    description: "Token-protected webcal feed for external calendar client subscriptions",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 10. Knowledge Base & AI Intelligence (5 Capabilities)
  // ===========================================================================
  {
    key: "knowledge_base",
    name: "Categorized Knowledge Base",
    description: "Searchable repository of company handbooks, benefit guides, and policies",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "kb_slideshow",
    name: "Fullscreen Presentation Slideshow",
    description: "Interactive slide deck presentation view for orientation documentation",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "ai_assistant",
    name: "Interactive AI Q&A Assistant",
    description: "Conversational AI agent answering questions regarding internal handbooks",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "rag_policy_search",
    name: "RAG Vector Search over Handbooks",
    description: "Retrieval-augmented generation leveraging semantic search across docs",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "ai_response_feedback",
    name: "AI Rating & Answer Feedback",
    description: "Thumbs up/down feedback logging to refine assistant response quality",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 11. Public Compliance & Cryptographic Verification (4 Capabilities)
  // ===========================================================================
  {
    key: "certificates",
    name: "Digital Completion Certificates",
    description: "Cryptographically verifiable graduation certificates upon journey completion",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "public_qr_verify",
    name: "Public QR Code Certificate Page",
    description: "Publicly accessible credential verification portal reached via QR scan",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "sha256_audit_seal",
    name: "SHA-256 Tamper-Evident Signatures",
    description: "Cryptographic digest seals ensuring certificates cannot be forged",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "cert_pdf_download",
    name: "Client PDF Certificate Render",
    description: "High-resolution PDF rendering suitable for candidate printing or framing",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },

  // ===========================================================================
  // 12. Super Admin Enterprise Control Plane (18 Capabilities)
  // ===========================================================================
  {
    key: "super_admin_core",
    name: "Super Admin Command Center Hub",
    description: "Centralized multi-tenant administration portal with global stats",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "tenant_oversight",
    name: "Organization 360 Dossier & Health",
    description: "Comprehensive tenant metadata, contract terms, and member statistics",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "tenant_lifecycle",
    name: "Tenant Quarantine & Suspension",
    description: "Immediate tenant isolation, maintenance mode, and status controls",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "user_360",
    name: "User 360 & Impersonation",
    description: "Deep diagnostic user profile inspection and secure support impersonation",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "session_tracker",
    name: "Active JWT Session Management",
    description: "Global real-time tracking of active user sessions across all organizations",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "session_kill",
    name: "Force User Logout & Kill Session",
    description: "Instant cryptographic invalidation of compromised user sessions",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "b2b_invoicing",
    name: "Itemized Invoice Engine",
    description: "Enterprise B2B invoicing with recurring subscriptions and line-item taxes",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "payment_receipts",
    name: "Partial Payment Reconciliation",
    description: "Audit-grade payment reconciliation supporting multiple partial payments",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "operating_expenses",
    name: "Authoritative Expense Tracking",
    description: "Internal infrastructure and operational cost accounting engine",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "customer_accounts",
    name: "Commercial Tiers & Credit Holds",
    description: "Commercial account terms, prepaid balances, and automated credit locks",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "api_ring_buffer",
    name: "Fastify Live Latency Telemetry",
    description: "In-memory circular telemetry buffer tracking endpoint latency & errors",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "ai_token_tracker",
    name: "AI Token & Cost Telemetry Buffer",
    description: "Token consumption and dollar expenditure tracking per tenant LLM request",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "alert_triage",
    name: "Incident Alert Lifecycle Engine",
    description: "Real-time system incident alerts with severity triage and resolution logs",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "advanced_reporting",
    name: "15 Streaming Canonical Reports",
    description: "Real-time streaming and export of compliance and audit reports",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "maintenance_guard",
    name: "Global Maintenance Mode Hook",
    description: "Platform-wide emergency traffic interruption for scheduled maintenance",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "feature_governance",
    name: "Feature Flag Overrides Center",
    description: "Granular organization and role overrides for all platform capabilities",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "feature_adoption",
    name: "Feature Adoption Telemetry View",
    description: "Analytics tracking tenant feature engagement and active usage percentages",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "cross_tenant_search",
    name: "Global Cross-Tenant Omnisearch",
    description: "Instant omnibar search finding tenants, users, and invoices globally",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "audit_log_viewer",
    name: "Platform Security Audit Trail",
    description: "Immutable, tamper-evident security audit log viewer with actor tracking",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "organization_export",
    name: "Tenant Data Portability & Archive",
    description: "Full JSON/CSV export of tenant organizational data for portability",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "security_policy_enforcement",
    name: "MFA & Session Timeout Guard",
    description: "Enterprise password complexity, MFA enforcement, and idle session limits",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "infra_telemetry",
    name: "Node & Database Health Observability",
    description: "Real-time Node.js event loop, memory, and MongoDB connection metrics",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "storage_telemetry",
    name: "S3 / Local Media Asset Metrics",
    description: "Storage utilization tracking across documents, videos, and avatars",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "revenue_recognition",
    name: "Deterministic MRR & ARR Accounting",
    description: "Accrual and recognized SaaS revenue calculations over contract terms",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "cash_reconciliation",
    name: "Authoritative Cash Collection Math",
    description: "Reconciliation of bank receipts against issued tenant invoices",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "tenant_credit_limits",
    name: "Enterprise Credit Hold Governance",
    description: "Credit limit enforcement freezing non-critical actions on overdue accounts",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "task_sla_monitoring",
    name: "Cross-Tenant SLA Bottleneck Heatmap",
    description: "Platform-wide bottleneck detection on task and milestone completions",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
  {
    key: "onboarding_funnels",
    name: "Cross-Tenant Onboarding Progression",
    description: "Cohort analytics visualizing velocity from invitation to graduation",
    isEnabled: true,
    rolloutPercentage: 100,
    targetAudience: "global",
    environment: "all",
  },
];
