export const DEMO_PACKAGES = {
  STANDARD: {
    name: "Standard Onboarding Demo",
    features: [
      "roadmap_timeline",
      "checklist_tasks",
      "journey_templates",
      "digital_signatures",
      "employee_directory",
      "buddy_connection",
      "knowledge_base",
    ],
  },
  EXECUTIVE: {
    name: "Executive Overview Demo",
    features: [
      "roadmap_timeline",
      "team_supervision",
      "analytics_dashboard",
      "milestone_ratings",
      "compliance_audit",
      "knowledge_base",
    ],
  },
  FULL_SUITE: {
    name: "Full Enterprise Suite Demo",
    features: [
      "roadmap_timeline",
      "checklist_tasks",
      "journey_templates",
      "journey_builder",
      "digital_signatures",
      "employee_directory",
      "buddy_connection",
      "milestone_ratings",
      "ai_assistant",
      "ai_course_builder",
      "knowledge_base",
      "office_map",
      "gamified_milestones",
      "team_supervision",
      "analytics_dashboard",
    ],
  },
};

export const DETERMINISTIC_DEMO_COMPANIES = [
  {
    name: "Acme Corporation Demo",
    slug: "acme-corp-demo",
    domain: "acme-demo.com",
    contactEmail: "admin@acme-demo.com",
    entitlementPackage: "FULL_SUITE" as const,
    allowedFeatures: DEMO_PACKAGES.FULL_SUITE.features,
    sessionLimit: 2,
  },
  {
    name: "Globex Industries Demo",
    slug: "globex-demo",
    domain: "globex-demo.com",
    contactEmail: "admin@globex-demo.com",
    entitlementPackage: "STANDARD" as const,
    allowedFeatures: DEMO_PACKAGES.STANDARD.features,
    sessionLimit: 1,
  },
];

export const DETERMINISTIC_DEMO_USERS = [
  {
    companySlug: "acme-corp-demo",
    email: "sarah.connor@acme-demo.com",
    fullName: "Sarah Connor",
    role: "demo_admin" as const,
    department: "Executive",
    jobTitle: "VP of People Operations",
  },
  {
    companySlug: "acme-corp-demo",
    email: "alice.smith@acme-demo.com",
    fullName: "Alice Smith",
    role: "demo_manager" as const,
    department: "Engineering",
    jobTitle: "Engineering Manager",
  },
  {
    companySlug: "acme-corp-demo",
    email: "john.doe@acme-demo.com",
    fullName: "John Doe",
    role: "demo_employee" as const,
    department: "Engineering",
    jobTitle: "Senior Frontend Engineer",
  },
  {
    companySlug: "acme-corp-demo",
    email: "david.kim@acme-demo.com",
    fullName: "David Kim",
    role: "demo_employee" as const,
    department: "Engineering",
    jobTitle: "Junior Software Engineer",
  },
  {
    companySlug: "acme-corp-demo",
    email: "elena.rostova@acme-demo.com",
    fullName: "Elena Rostova",
    role: "demo_employee" as const,
    department: "Product & Design",
    jobTitle: "Principal Product Designer",
  },
  {
    companySlug: "acme-corp-demo",
    email: "marcus.chen@acme-demo.com",
    fullName: "Marcus Chen",
    role: "demo_employee" as const,
    department: "Engineering",
    jobTitle: "DevOps & Infrastructure Lead",
  },
  {
    companySlug: "acme-corp-demo",
    email: "rachel.green@acme-demo.com",
    fullName: "Rachel Green",
    role: "demo_manager" as const,
    department: "People & Culture",
    jobTitle: "Head of People Experience",
  },
  {
    companySlug: "acme-corp-demo",
    email: "michael.scott@acme-demo.com",
    fullName: "Michael Scott",
    role: "demo_manager" as const,
    department: "Sales",
    jobTitle: "Regional Director",
  },
  {
    companySlug: "globex-demo",
    email: "bob.vance@globex-demo.com",
    fullName: "Bob Vance",
    role: "demo_admin" as const,
    department: "Sales",
    jobTitle: "Director of Business Development",
  },
  {
    companySlug: "globex-demo",
    email: "jim.halpert@globex-demo.com",
    fullName: "Jim Halpert",
    role: "demo_employee" as const,
    department: "Sales",
    jobTitle: "Senior Account Executive",
  },
  {
    companySlug: "globex-demo",
    email: "pam.beesly@globex-demo.com",
    fullName: "Pam Beesly",
    role: "demo_employee" as const,
    department: "Operations",
    jobTitle: "Office & People Coordinator",
  },
];

export const DETERMINISTIC_DEMO_JOURNEYS = [
  {
    companySlug: "acme-corp-demo",
    title: "Engineering Onboarding Roadmap (Day 1 - 30)",
    description: "Comprehensive software engineering ramp covering architecture, local development setup, CI/CD pipelines, and your first production deployment.",
    category: "Engineering",
    durationDays: 30,
    modulesCount: 3,
    status: "published" as const,
    publishing: { status: "published" as const, publishedAt: new Date(Date.now() - 30 * 86400000).toISOString() },
    analytics: { totalAssignments: 18, completionRate: 82 },
    modules: [
      {
        _id: "mod-eng-1",
        title: "Day 1: Architecture & Local Dev Environment",
        lessons: [
          {
            _id: "les-eng-1-1",
            title: "Welcome to Acme Engineering & Architecture Topology",
            description: "High-level overview of our microservices, API gateway, MongoDB clusters, and Redis caching layers.",
            type: "Video" as const,
            estimatedDurationMinutes: 10,
            contentBlocks: [{ type: "video", content: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" }],
          },
          {
            _id: "les-eng-1-2",
            title: "Configuring Node.js, Docker & Local Dev Stacks",
            description: "Step-by-step instructions for installing package dependencies, Docker Compose services, and local SSL certificates.",
            type: "Article" as const,
            estimatedDurationMinutes: 15,
            contentBlocks: [{ type: "paragraph", content: "Ensure you have Node 20+ and Docker Desktop installed. Clone the repository and run `npm run setup`." }],
          },
          {
            _id: "les-eng-1-3",
            title: "Dev Environment Verification Check",
            description: "Quick 3-question knowledge check ensuring your local environment meets security standards.",
            type: "Quiz" as const,
            estimatedDurationMinutes: 5,
            quiz: {
              id: "quiz-eng-1",
              passingScore: 80,
              questions: [
                {
                  id: "q-1",
                  question: "What is the minimum required Node.js version?",
                  type: "single_choice",
                  points: 1,
                  options: [
                    { id: "opt-1", text: "Node 16", isCorrect: false },
                    { id: "opt-2", text: "Node 20+", isCorrect: true },
                    { id: "opt-3", text: "Node 14", isCorrect: false },
                  ],
                },
                {
                  id: "q-2",
                  question: "Where are sensitive environment variables stored locally?",
                  type: "single_choice",
                  points: 1,
                  options: [
                    { id: "opt-4", text: "Committed in git", isCorrect: false },
                    { id: "opt-5", text: "1Password CLI / .env.local", isCorrect: true },
                  ],
                },
              ],
            },
          },
        ],
      },
      {
        _id: "mod-eng-2",
        title: "Week 1: Code Review, CI/CD & Testing Standards",
        lessons: [
          {
            _id: "les-eng-2-1",
            title: "Pull Request Guidelines & Code Owner Reviews",
            description: "Our standards for PR titles, commit hygiene, automated test coverage, and constructive peer reviews.",
            type: "Article" as const,
            estimatedDurationMinutes: 12,
            contentBlocks: [{ type: "paragraph", content: "All PRs require 2 code owner approvals. Keep diffs under 400 lines whenever possible." }],
          },
          {
            _id: "les-eng-2-2",
            title: "Deploying Your First Canary to Staging",
            description: "Hands-on walkthrough for triggering GitHub Actions workflows and verifying staging health checks.",
            type: "Task" as const,
            estimatedDurationMinutes: 20,
            contentBlocks: [{ type: "paragraph", content: "Open a test PR with a documentation tweak and observe the preview deployment." }],
          },
        ],
      },
      {
        _id: "mod-eng-3",
        title: "Month 1: Observability, Metrics & On-Call Rotation",
        lessons: [
          {
            _id: "les-eng-3-1",
            title: "Navigating Prometheus Dashboards & Datadog Logs",
            description: "How to inspect request latencies, error budgets, and distributed trace spans across services.",
            type: "Article" as const,
            estimatedDurationMinutes: 15,
            contentBlocks: [{ type: "paragraph", content: "Use standard tags: service, env, and tenantId when filtering log streams." }],
          },
        ],
      },
    ],
  },
  {
    companySlug: "acme-corp-demo",
    title: "Company Culture, Core Values & Benefits Immersion",
    description: "Essential introduction to Acme's mission, remote work flexibility, employee resource groups, and comprehensive healthcare benefits.",
    category: "People & Culture",
    durationDays: 14,
    modulesCount: 2,
    status: "published" as const,
    publishing: { status: "published" as const, publishedAt: new Date(Date.now() - 40 * 86400000).toISOString() },
    analytics: { totalAssignments: 26, completionRate: 94 },
    modules: [
      {
        _id: "mod-cul-1",
        title: "Welcome to Acme & Our Operating Principles",
        lessons: [
          {
            _id: "les-cul-1-1",
            title: "A Message from Our Leadership Team",
            description: "Hear from founders and department leads on what drives our mission and customer obsession.",
            type: "Video" as const,
            estimatedDurationMinutes: 8,
            contentBlocks: [{ type: "video", content: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" }],
          },
          {
            _id: "les-cul-1-2",
            title: "Our 4 Core Values: Velocity, Empathy, Transparency, Ownership",
            description: "Deep dive into how we make decisions, share feedback candidly, and empower every team member.",
            type: "Article" as const,
            estimatedDurationMinutes: 10,
            contentBlocks: [{ type: "paragraph", content: "We default to open communication, assume positive intent, and bias towards action." }],
          },
        ],
      },
      {
        _id: "mod-cul-2",
        title: "Perks, Wellness & Healthcare Navigation",
        lessons: [
          {
            _id: "les-cul-2-1",
            title: "Comprehensive Benefits & 401(k) Matching Guide",
            description: "Everything you need to know about medical, dental, vision, mental health subsidies, and retirement plans.",
            type: "Document" as const,
            estimatedDurationMinutes: 15,
            contentBlocks: [{ type: "document", content: "Benefits begin on day 1. Review your options and enroll within 30 days." }],
          },
        ],
      },
    ],
  },
  {
    companySlug: "acme-corp-demo",
    title: "Security Compliance & Phishing Defense 2026",
    description: "Annual cybersecurity certification covering Zero Trust protocols, hardware MFA, customer data protection, and incident reporting.",
    category: "Company Policies",
    durationDays: 7,
    modulesCount: 2,
    status: "published" as const,
    publishing: { status: "published" as const, publishedAt: new Date(Date.now() - 20 * 86400000).toISOString() },
    analytics: { totalAssignments: 34, completionRate: 98 },
    modules: [
      {
        _id: "mod-sec-1",
        title: "Hardware Security & Zero Trust Authentication",
        lessons: [
          {
            _id: "les-sec-1-1",
            title: "1Password Enterprise & FIDO2 Security Keys",
            description: "Enforce biometrics, hardware security keys, and encrypted password vaults across all corporate accounts.",
            type: "Article" as const,
            estimatedDurationMinutes: 10,
            contentBlocks: [{ type: "paragraph", content: "Never reuse passwords or store credentials in unencrypted text files." }],
          },
        ],
      },
      {
        _id: "mod-sec-2",
        title: "Phishing Simulations & Social Engineering Awareness",
        lessons: [
          {
            _id: "les-sec-2-1",
            title: "Spotting Deepfakes & Spear-Phishing Attacks",
            description: "Real-world examples of modern executive impersonation and AI voice synthesis scams.",
            type: "Video" as const,
            estimatedDurationMinutes: 8,
            contentBlocks: [{ type: "video", content: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" }],
          },
          {
            _id: "les-sec-2-2",
            title: "2026 Security Certification Quiz",
            description: "Mandatory certification quiz required for SOC2 compliance.",
            type: "Quiz" as const,
            estimatedDurationMinutes: 5,
            quiz: {
              id: "quiz-sec-1",
              passingScore: 100,
              questions: [
                {
                  id: "qs-1",
                  question: "What should you do if you receive an unexpected email requesting urgent gift cards?",
                  type: "single_choice",
                  points: 1,
                  options: [
                    { id: "o-1", text: "Buy the gift cards immediately", isCorrect: false },
                    { id: "o-2", text: "Click Report Phishing in Slack/Email", isCorrect: true },
                  ],
                },
              ],
            },
          },
        ],
      },
    ],
  },
  {
    companySlug: "globex-demo",
    title: "Sales Representative Acceleration Path",
    description: "Product demonstration certifications, objection handling battlecards, and CRM pipeline hygiene onboarding.",
    category: "Sales",
    durationDays: 21,
    modulesCount: 2,
    status: "published" as const,
    publishing: { status: "published" as const, publishedAt: new Date(Date.now() - 15 * 86400000).toISOString() },
    analytics: { totalAssignments: 10, completionRate: 90 },
    modules: [
      {
        _id: "mod-sal-1",
        title: "Enterprise Product Mastery",
        lessons: [
          {
            _id: "les-sal-1-1",
            title: "Platform Feature Matrix & Architecture Pitch",
            description: "How to effectively articulate platform ROI and security architecture to CISOs.",
            type: "Article" as const,
            estimatedDurationMinutes: 15,
            contentBlocks: [{ type: "paragraph", content: "Focus on automated onboarding velocity and compliance risk reduction." }],
          },
        ],
      },
    ],
  },
];

export const DETERMINISTIC_DEMO_TASKS = [
  {
    companySlug: "acme-corp-demo",
    title: "Configure 1Password & MFA Hardware Keys",
    description: "Set up enterprise password manager and register your YubiKey / FIDO2 biometric security device.",
    category: "it_setup" as const,
    stage: "preboarding" as const,
    priority: "critical" as const,
    status: "completed" as const,
    dueDays: 1,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Order Workstation & Ergonomic Hardware",
    description: "Select laptop hardware specifications and optional 4K monitor through the IT Hardware procurement portal.",
    category: "equipment" as const,
    stage: "preboarding" as const,
    priority: "high" as const,
    status: "completed" as const,
    dueDays: 2,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Submit Signed W-4 & Direct Deposit Form",
    description: "Review and electronically sign official tax withholding and payroll direct deposit authorization.",
    category: "hr_paperwork" as const,
    stage: "day_1" as const,
    priority: "critical" as const,
    status: "completed" as const,
    dueDays: 2,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Schedule 1-on-1 Coffee Chat with Onboarding Buddy",
    description: "Book an informal introductory 30-minute chat with your assigned engineering peer mentor (Alice Smith).",
    category: "general" as const,
    stage: "day_1" as const,
    priority: "normal" as const,
    status: "completed" as const,
    dueDays: 3,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Review Architecture Guidelines & Clone Core Repositories",
    description: "Clone the core mono-repo, review Docker container setups, and verify local build pipelines.",
    category: "training" as const,
    stage: "week_1" as const,
    priority: "high" as const,
    status: "in_progress" as const,
    dueDays: 5,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Complete 2026 Anti-Harassment & Compliance Module",
    description: "Mandatory annual workplace culture and non-discrimination certification video and quiz.",
    category: "training" as const,
    stage: "week_1" as const,
    priority: "high" as const,
    status: "in_progress" as const,
    dueDays: 7,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Submit First Pull Request & Review CI/CD Checks",
    description: "Submit a starter feature PR, request review from your onboarding buddy, and verify automated deployment to staging.",
    category: "training" as const,
    stage: "week_1" as const,
    priority: "normal" as const,
    status: "pending" as const,
    dueDays: 8,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Schedule 30-Day Mentorship & Manager Touchpoint",
    description: "Reflect on first month milestones, onboarding feedback, and roadmap goals with your engineering manager.",
    category: "general" as const,
    stage: "month_1" as const,
    priority: "normal" as const,
    status: "pending" as const,
    dueDays: 28,
  },
  {
    companySlug: "globex-demo",
    title: "Complete Anti-Harassment Compliance Module",
    description: "Annual workplace compliance certification video and quiz.",
    category: "training" as const,
    stage: "day_1" as const,
    priority: "high" as const,
    status: "pending" as const,
    dueDays: 5,
  },
];

export const DETERMINISTIC_DEMO_DOCUMENTS = [
  {
    companySlug: "acme-corp-demo",
    title: "Confidentiality and Proprietary Information Agreement",
    documentType: "nda" as const,
    category: "nda" as const,
    status: "pending_signature" as const,
    content: "### Non-Disclosure & Intellectual Property Agreement\n\nThis Agreement is entered into by and between Acme Corporation and the Employee. Employee agrees to protect all trade secrets, source code, and customer records under strict confidentiality.",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Direct Deposit Enrollment Authorization",
    documentType: "direct_deposit" as const,
    category: "direct_deposit" as const,
    status: "signed" as const,
    content: "### Direct Deposit Enrollment\n\nI hereby authorize Acme Corporation to initiate credit entries to my verified checking account for payroll processing.",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Standard Code of Business Ethics & Conduct",
    documentType: "code_of_conduct" as const,
    category: "code_of_conduct" as const,
    status: "pending_signature" as const,
    content: "### Code of Conduct\n\nAll team members are expected to conduct business with honesty, integrity, and adherence to all applicable laws and compliance guidelines.",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Remote Work & Hardware Security Policy",
    documentType: "nda" as const,
    category: "nda" as const,
    status: "pending_signature" as const,
    content: "### Remote Work Policy\n\nCompany hardware must remain encrypted, password-protected, and used strictly in accordance with Acme security policies.",
  },
  {
    companySlug: "globex-demo",
    title: "Standard Code of Business Ethics",
    documentType: "code_of_conduct" as const,
    category: "code_of_conduct" as const,
    status: "pending_signature" as const,
    content: "### Globex Code of Conduct\n\nCompliance principles and sales ethics for all Globex team members.",
  },
];

export const DETERMINISTIC_DEMO_KB_ARTICLES = [
  {
    companySlug: "acme-corp-demo",
    title: "Welcome to Acme: Company Handbook & Core Culture",
    category: "Employee Handbook",
    summary: "Essential guidance on Acme values, hybrid work expectations, communication norms, and employee wellness.",
    content: "### Our Mission\nAt Acme, we build mission-critical enterprise software with zero compromise on quality and security.\n\n### Working Hours & Flexibility\nCore collaboration hours are 10:00 AM to 4:00 PM local time. Outside of core hours, asynchronous communication via Slack and Jira is encouraged.\n\n### Benefits & Equipment\nFull health, dental, and vision insurance begins on day 1. Each employee receives a $1,500 annual home office stipend.",
    readTimeMinutes: 4,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Working Hours, Core Overlap & Flexible Time Off (FTO)",
    category: "Employee Handbook",
    summary: "How flexible time off works, requesting leave, core overlap hours, and sabbatical eligibility.",
    content: "### Flexible Time Off (FTO)\nAcme offers flexible paid time off to recharge. Coordinate with your manager at least two weeks in advance for planned leaves exceeding 3 consecutive days.",
    readTimeMinutes: 3,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Engineering Development Standards & CI/CD Guidelines",
    category: "Engineering Guidelines",
    summary: "Branching strategies, PR review criteria, deployment gates, and security scan compliance requirements.",
    content: "### Pull Request Etiquette\n- All PRs require at least 2 approvals from team code owners.\n- Automated test coverage must not decrease.\n- Static analysis (SonarQube) must pass without blockers.\n\n### Deployment Protocol\nAutomated CI/CD pipelines run on GitHub Actions. Deployments to staging occur automatically upon main merge.",
    readTimeMinutes: 6,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Production Incident Severity Matrix & On-Call Escalation",
    category: "Engineering Guidelines",
    summary: "PagerDuty escalation tiers, incident commander roles, status page communications, and blameless post-mortems.",
    content: "### Severity Tiers\n- **SEV-1 (Critical):** Core customer outage. Page on-call immediately; declare in #incident-command.\n- **SEV-2 (Major):** Degradation of non-critical services. Response within 15 minutes.\n\n### Blameless Culture\nPost-mortems focus on systemic safeguards, automated alerts, and defense-in-depth.",
    readTimeMinutes: 5,
  },
  {
    companySlug: "acme-corp-demo",
    title: "IT Security Protocols & Device Compliance",
    category: "Company Policies",
    summary: "Device encryption, password management, VPN requirements, and incident reporting procedures.",
    content: "### Hardware Requirements\nAll company-issued laptops must enforce FileVault / BitLocker disk encryption and automatic screen lock after 5 minutes of inactivity.\n\n### Credential Protection\nNever share passwords via chat or email. Use the corporate 1Password vault for all shared operational secrets.",
    readTimeMinutes: 3,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Remote Work Stipend & Equipment Expensing Policy",
    category: "Company Policies",
    summary: "Eligible items for home office setup, reimbursement limits, and submission guidelines via Expensify.",
    content: "### Eligible Expenses\n- Ergonomic desk chairs and standing desk converters (up to $800)\n- External 4K monitors and ergonomic keyboards/mice (up to $500)\n- Monthly broadband internet subsidy ($75/month)",
    readTimeMinutes: 4,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Healthcare Benefits, 401(k) Match & Wellness Stipend",
    category: "HR & People",
    summary: "Medical, dental, vision coverage details, 4% employer 401(k) match, and monthly fitness subsidies.",
    content: "### Coverage Overview\nChoose between PPO and HDHP with HSA contribution. 401(k) matching vests immediately at 100% up to 4% of base compensation.",
    readTimeMinutes: 5,
  },
  {
    companySlug: "acme-corp-demo",
    title: "Annual Performance Review & Career Progression Ladder",
    category: "HR & People",
    summary: "Engineering, product, and leadership competency matrices, 360-degree feedback cycles, and promotion windows.",
    content: "### Review Cycles\nBi-annual performance reviews take place in June and December. Career ladders are publicly accessible across all tracks (IC and Manager).",
    readTimeMinutes: 4,
  },
  {
    companySlug: "globex-demo",
    title: "Sales Playbook & Opportunity Qualification",
    category: "Company Policies",
    summary: "BANT qualification framework, pricing discount matrix, and CRM pipeline hygiene standards.",
    content: "### Qualification Matrix\nEvery deal in Stage 2+ must document Budget, Authority, Need, and Timeline directly in Salesforce.",
    readTimeMinutes: 5,
  },
];

export const DETERMINISTIC_DEMO_MILESTONES = [
  {
    companySlug: "acme-corp-demo",
    title: "Day 1 Explorer",
    description: "Successfully set up credentials, completed identity verification, and logged into the onboarding portal.",
    points: 100,
    badgeIcon: "zap",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Security Champion",
    description: "Completed MFA hardware key registration and passed the 2026 phishing defense simulation.",
    points: 250,
    badgeIcon: "shield-check",
  },
  {
    companySlug: "acme-corp-demo",
    title: "First PR Merged",
    description: "Submitted your first code change, received peer review approval, and deployed to staging.",
    points: 500,
    badgeIcon: "code",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Culture Ambassador",
    description: "Completed the company core values immersion course and connected with an onboarding buddy.",
    points: 150,
    badgeIcon: "heart",
  },
  {
    companySlug: "acme-corp-demo",
    title: "Fast Learner",
    description: "Completed all preboarding and first-week tasks ahead of scheduled deadlines.",
    points: 200,
    badgeIcon: "book-open",
  },
  {
    companySlug: "globex-demo",
    title: "Sales Certified",
    description: "Passed the product demonstration exam and completed simulated discovery call.",
    points: 300,
    badgeIcon: "award",
  },
];
